version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
      include: "scope"
    groups:
      kube-rs-k8s-openapi:
        patterns:
          - "kube"
          - "k8s-openapi"