apiVersion: v1
kind: Secret
metadata:
  name: simple-secret-username-cron
  annotations:
    v1.secret.runo.rocks/generate-0: username
    v1.secret.runo.rocks/length-0: "8"
    v1.secret.runo.rocks/regeneration-cron-0: "0 * * * *"
type: Opaque
data:
  username: "ZGFzZGFzZAo="