apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runo-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runo-controller
subjects:
  - namespace: kube-system
    kind: ServiceAccount
    name: runo-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runo-cronjob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runo-cronjob
subjects:
  - namespace: default
    kind: ServiceAccount
    name: runo-cronjob