name: build

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Check test coverage with tarpaulin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.7.0
        with:
          cluster_name: "kind"
      - name: "Apply RBAC resources"
        run: kubectl apply -k rbac
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest
      - run: cargo tarpaulin --timeout 300 -o Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
  build:
    name: Build a new version of runo
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build binary
        run: cargo build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: target/debug/runo
      
