name: release

on:
  push:
    tags:
      - v*.*.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build a release version of runo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - { target: aarch64-unknown-linux-gnu, platform: linux/arm64 }
          - { target: x86_64-unknown-linux-gnu, platform: linux/amd64 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.recipe.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.recipe.target }} --release
      - name: Rename binary
        run: cp target/${{ matrix.recipe.target }}/release/runo ${{ matrix.recipe.target }}
      - name: Generate checksum
        run: |
          sha256sum ${{ matrix.recipe.target }} > checksum.txt
      - name: Archive checksum.txt
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.recipe.target }}-checksum
          path: checksum.txt
          retention-days: 30
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.recipe.target }}
          path: target/${{ matrix.recipe.target }}/release/runo
          retention-days: 30
  release:
    name: Create a Github release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: convco
          version: latest
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-release
          version: latest
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Merge checksum.txt files
        run: for i in  *-checksum ; do cat $i/checksum.txt >> checksums.txt; done
      - name: Generate changelog
        run: |
          convco changelog $(git tag --list --sort=version:refname | tail -2 | head -1 )..$(git tag --list --sort=version:refname | tail -1 ) > CHANGELOG.md
      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "checksums.txt"
          bodyFile: "CHANGELOG.md"
  image:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: release
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - { target: aarch64-unknown-linux-gnu, platform: linux/arm64 }
          - { target: x86_64-unknown-linux-gnu, platform: linux/amd64 }
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.recipe.target }}
      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.recipe.platform }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}" 
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  merge:
    runs-on: ubuntu-latest
    needs:
      - image
    permissions:
        contents: read
        packages: write
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          name: digests
          path: /tmp/digests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)