name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests with cargo test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v1.28.15, v1.29.14, v1.30.10, v1.31.6, v1.32.3, v1.33.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: "kind"
          node_image: kindest/node:${{ matrix.version }}
      - name: "Apply RBAC resources"
        run: kubectl apply -k rbac
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test
