name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests with cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.7.0
        with:
          cluster_name: "kind"
      - name: "Apply RBAC resources"
        run: kubectl apply -k rbac
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test